#!/usr/bin/env bash
# this is a Bash script install nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i 's/listen [^;]*;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx reload
