#!/usr/bin/env bash
# this is a Bash script that transfers a file from our client to a server

apt update -y
apt install nginx -y
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
