#!/usr/bin/env bash
# this is a Bash script redirect

if ! nginx -v; then
apt-get update
apt-get install -y nginx
fi

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

redirect_link="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s|server_name _;|$redirect_link|" /etc/nginx/sites-enabled/default

sudo service nginx restart
