#!/usr/bin/env bash
# this is a Bash script redirect

if ! nginx -v; then
apt-get update
apt-get install -y nginx
fi

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
redirect_link="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https://youtu.be/CmdNJnkR6fw?si=rryJbTXwhdXOsnkS;\n\t}"
sed -i "s|server_name _;|$redirect_link|" /etc/nginx/sites-available/default
nginx
