#!/usr/bin/env bash
# this is a Bash script configure the 404page

if ! nginx -v; then
apt-get update
apt-get install -y nginx
fi

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
redirect_link="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https://youtu.be/CmdNJnkR6fw?si=rryJbTXwhdXOsnkS;\n\t}"
sed -i "s|server_name _;|$redirect_link|" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
error_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s|listen 80 default_server;|$error_404|" /etc/nginx/sites-available/default
nginx
