#!/usr/bin/env bash
# this script configure a the server http response to indicate the server host

if ! nginx -v; then
apt-get update
apt-get install -y nginx
fi

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

redirect_link="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=CmdNJnkR6fw;\n\t}"
sudo sed -i "s|server_name _;|$redirect_link|" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|listen 80 default_server;|$error_404|" /etc/nginx/sites-enabled/default

hostname=$(sudo hostname)
httphostname="index index.html index.htm index.nginx-debian.html;\n\n\t# Add custom response headers\n\tadd_header X-Served-By \"$hostname\";\n"
sudo sed -i "s|index index.html index.htm index.nginx-debian.html;|$httphostname|" /etc/nginx/sites-enabled/default

sudo service nginx restart

