#!/usr/bin/env bash
# this script install the HAproxy and configure it for two backend servers

# haproxy installation
sudo apt-get install -y update
sudo apt-get install -y haproxy

# haproxy configuration
sudo sh -c 'echo "\nfrontend frontend_server\n\tbind *:80\n\tdefault_backend backend_server\n\nbackend backend_server\n\tbalance \troundrobin\n\tserver 86607-web-01\t35.175.126.167:80 check\n\tserver 86607-web-02\t18.206.197.223:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service restart haproxy
