#!/usr/bin/env bash
# This script configure Nginx to be running,
# and listening on port 80 of all the server’s active IPv4 IPs
sudo python3 -m http.server --directory /usr/share/nginx/html 80 > /dev/null 2>&1 &
