#!/usr/bin/env bash
#This script is displaying "Best School" 9 times and "Hi" at 9th iteration

i=1
while [ $i -le 10 ]; do
if [ $i == 9 ]; then
    echo "Hi"
else
    echo "Best School"
fi
((i++))
done