#!/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

my_list=$(ls)
for item in $my_list; do
echo "$item" | cut -d'-' -f 2
done
