#!/bin/env bash
# A Bash script that gives you information about the school file.

# Requirements:

# You must use if and, else (case is forbidden)
# Your Bash script should check if the file exists and print:
#       if the file exists: school file exists
#       if the file does not exist: school file does not exist
# If the file exists, print:
#       if the file is empty: school file is empty
#       if the file is not empty: school file is not empty
#       if the file is a regular file: school is a regular file
#       if the file is not a regular file: (nothing)

hidden="school"

if [ -e $hidden ]; then
    echo "$hidden file exists"
    if [ -s $hidden ]; then
        echo "$hidden is not empty"
    else
        echo "$hidden is empty"
    fi

    if [ -f $hidden ]; then
        echo "$hidden is a regular file"
    fi

else
    echo "$hidden file is empty"
fi
