#!/usr/bin/env bash
# this bash script configures the container with these nginx must be running as nginx user nginx must be listening on all active IPs on port 8080
sed -i 's|user www-data|user nginx|' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's|80|8080|g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
